name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # If you need to build your static site, add build steps here
      # For example, for React/Vue/Angular, add npm install/build steps

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Change this if your static files are in a different folder
